import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedApiBloc {
  final List<ApiBlocModel> results;

  AutogeneratedApiBloc({this.results});

  factory AutogeneratedApiBloc.fromJson(Map<String, dynamic> json) {
    List<ApiBlocModel> temp;
    if (json['results'] != null) {
      temp = List<ApiBlocModel>();
      json['results'].forEach((v) {
        temp.add(ApiBlocModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedApiBloc(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ApiBlocModel extends Equatable {
  final int id;
  final String name;

  ApiBlocModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ApiBlocModel.fromJson(Map<String, dynamic> json) {
    return ApiBlocModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}
